-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.posts
(
    post_id bigserial NOT NULL,
    used_id bigint NOT NULL,
    title character varying NOT NULL,
    content text NOT NULL,
    creation_date timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_date timestamp without time zone,
    CONSTRAINT pk_post_id PRIMARY KEY (post_id)
);

COMMENT ON TABLE public.posts
    IS 'user posts';

CREATE TABLE IF NOT EXISTS public.users
(
    user_id bigserial NOT NULL,
    username character varying(255) NOT NULL,
    email character varying(255),
    password_hash character varying(255) NOT NULL,
    registration_date timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_user_id PRIMARY KEY (user_id)
);

COMMENT ON TABLE public.users
    IS 'user table';

ALTER TABLE IF EXISTS public.posts
    ADD CONSTRAINT fk_user_id FOREIGN KEY (used_id)
    REFERENCES public.users (user_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;

COMMENT ON CONSTRAINT fk_user_id ON public.posts
    IS 'foreign key reference the user tables user_id';


END;