-- SEEDING DATA FOR BLOG DATABASE
TRUNCATE TABLE public.comments, public.posts, public.users RESTART IDENTITY CASCADE;

-- Insert users
INSERT INTO public.users (username, email, password_hash) VALUES
  ('ythomas', 'lwilliams@gmail.com', '4c824c6beef95c395a3e208c077ab348867aefd07ad7ff02efa7530da11607ba'),
  ('manningkari', 'davidbarnes@yahoo.com', '3f67b80c794a02b3795c30c82d8ed746ceae4085097e8c51ce43043dd87f01c3'),
  ('bsimmons', 'mnavarro@bowman.net', '8bb234134fbe85735aaa8498e3c65aeb36e5376d68262d82cec972b6a371d728'),
  ('erica59', 'james24@gmail.com', 'afd210b1d21f2b67b2d9f928491eccd1679e083a789b2dd7f407ebc0e88f1a84'),
  ('justin24', 'madelinekaufman@lee.net', 'd8a87a1acadf2f93d527ce7a12e33d02bd1c06539367c426f7e74c4553b0f631'),
  ('charrell', 'joneslinda@dalton.info', '178d37b827861b5314f65fa7c457a43925083167322ddc0c539b871787f8a04d'),
  ('fjones', 'ksampson@gmail.com', 'a2acdf99050b9d1485714acaf4294241e215d194fa306914aeb21449cef350a1'),
  ('rchang', 'lewismalik@gmail.com', 'd768d3c6472698ac28a07c722221a76c558c193d8cc5b71e6178554b6ff585b5'),
  ('jessica26', 'davidstevens@huber.com', 'c68cccd19267aaefefcbbfeb40208408599fe470d52ea99e5978b6c2a31c59ba'),
  ('robert60', 'karenpittman@gmail.com', '0b5c0dae6c744ba5ee6f97acd99a5ca7b303b40270974f302d68066948bbd2fe'),
  ('mmiller', 'donna40@hotmail.com', '3d87062caaf8c6c8414f21e15510cd805923e926fceae7a25f7fd6e455c08257'),
  ('stevenward', 'valeriegriffin@perez.info', '1093ecee9f5f7fe352f47f21957901a921bb5f07a23adef52d7f08131dea4a41'),
  ('grichardson', 'lesliewilkins@white.info', '221d9b3e26764845e14696b6225380869f343202559d6e76536c53b05ffba9d4'),
  ('bjohnson', 'natasha30@osborne-smith.net', '16aefa44b9b2f5fb49b6b49575aa3dd611cad5bb8638f6c123daf8694b073a94'),
  ('gbanks', 'kyle74@hotmail.com', '4ac48a49de36b553df083ed7649b06865167cea8252013a6ff1b3c80044f8c85'),
  ('ralvarez', 'nicolechaney@garcia.com', 'de77776b4e4ecccde8ec826e2e20e9c5f1036bc52730c762170b0c185a959963'),
  ('ashleysalinas', 'mayerchad@gmail.com', '01b5db8e74936209dd0a6d7a01fe76d79acbbe6653366c18af4fae3b1f327bd6'),
  ('ymclean', 'angelawilson@yahoo.com', '075207acd83480c337c3c5ff37c13f233053c458fc54f31826d9bbb8af391dd3'),
  ('qmendoza', 'sean49@gonzalez-fletcher.biz', '85658dee0098fb19e8d9c3a947eba7aa42475fdb7df3694524881609f69621da'),
  ('michaelholland', 'hjohnson@gray-anderson.com', 'ed2cae5733f764024eb863dac522cfa157d04e7184bb791c45d0c2d3c06e7e73');

-- Insert posts
INSERT INTO public.posts (used_id, title, content) VALUES
  (17, 'Little worry me prevent follow music several.', 'Send board can baby class outside. Somebody mouth lose of attorney word. Low bar green dream.'),
  (18, 'Money player effect pattern both might.', 'Find total generation song claim. Factor mission entire data about million. Lead long Mr material. Sense minute still method follow feel research.'),
  (3, 'Water paper reveal price me by.', 'In unit system trial left field. Power remain hard get carry those. Main there yeah now important. Early anything since. Community brother seat matter player most. Light tonight above why pick get.'),
  (2, 'She former just church huge behavior cause.', 'Management include age relationship fish others environment. Provide resource throughout kind work walk local together. Nice huge myself into half ready.'),
  (7, 'Third rather artist everything coach.', 'All money series pressure. Heart general money career. Suggest single film data option.'),
  (1, 'Cold see pay region tell animal agree.', 'Believe however speak program data off force. Goal sell economic day foreign. Free she college necessary parent. Goal whom toward what. City note late necessary control knowledge. Support should work include throughout another energy.'),
  (3, 'Attorney find building try.', 'Third wife analysis require painting drug next kitchen. He bad environmental ability various this. Up protect beat art.'),
  (17, 'Particular again full organization.', 'Doctor employee benefit to series. Ahead return management wish traditional position pull hot. Country research surface. Find after performance fill.'),
  (5, 'Suffer interesting skill they really summer.', 'Around return force great. Participant respond specific once. Citizen option home mind. Finally throughout attorney record new contain north. Type apply such hundred within. Land until long.'),
  (2, 'Letter whether political night now office.', 'Security weight quality difference. Should source act. Nothing everybody himself become about send step. Name range but social base.'),
  (20, 'Throw management hard tell operation.', 'Relate thus area movement ball. Walk scene college industry. Throw exactly everybody.'),
  (7, 'Hotel almost director decade.', 'Impact clear campaign key especially home. Surface floor decide Mr capital style. Sister attack week energy civil. By accept name car figure kid. Current away would impact start community.'),
  (5, 'Design own step reach music benefit series.', 'Sell think place simply purpose. Right thought near hard pull. Successful north include region avoid skin that.'),
  (6, 'Assume set part save put minute back.', 'Serious including beautiful. Left born trial sound car economy address trip. Share bit few reduce move. Trial score safe still allow politics hear. Bring fact work. Blue ask authority receive.'),
  (6, 'These none pretty audience modern receive trade.', 'Arm business middle main remain lot focus. Answer author method yet paper. Upon concern painting power carry. Authority more enjoy according common. Camera forget special few sure major send. Many begin kind.'),
  (2, 'Learn deal class box.', 'Know realize impact work series fill beyond. Other perform paper as. That let tonight lay everyone protect nature water. Huge democratic organization responsibility popular nor. Head them Congress argue course.'),
  (8, 'Memory computer president board much professional.', 'Through available close. Beat represent official probably street than piece. Grow however participant sea responsibility meeting. Region beautiful local instead term live people though.'),
  (11, 'Mouth future all imagine test value.', 'Theory president father program. Doctor raise spend poor such. Individual from much then. Scientist war standard guy second. Technology report represent serve.'),
  (14, 'Would stop grow boy color history trouble those.', 'Report sport lawyer conference public far. Hundred rich chance address minute she. Her sing wind population feeling. Fill watch happy possible rate government case. Various media billion offer tend. Nothing lose direction environmental real exist make.'),
  (2, 'Rise including against north thing.', 'Response religious performance kind Congress. Upon deal north. Whatever style treat weight property. Must environment agree along agreement.'),
  (16, 'Sometimes need drop we help believe simply.', 'Window tough guy someone. Fly determine ago shake most pass simply control. About experience mother however focus. Tough course bad work administration natural plan. Play game art message artist organization part. Network less or out late.'),
  (14, 'Pattern here hit.', 'Strategy such million. Act build increase north. Well feel position any. Picture within defense only few.'),
  (1, 'Hot onto other forget method artist.', 'Myself use company tax still. Population customer night option. Friend church actually statement teach unit country institution.'),
  (7, 'Season fast really movement reduce different point road.', 'Window treat agency close information course. Center finish teacher position their responsibility create. Watch plan better here. Five administration name record late.'),
  (15, 'Leg body life crime parent whatever word.', 'Senior use song hit new sign. When price responsibility. Bag history money wait daughter city.'),
  (2, 'Business traditional control challenge machine especially.', 'Dog herself hit international future describe not. Attention along card popular usually top. Could foot weight wall. Health pull care everyone.'),
  (16, 'About leg up together during public organization ground.', 'Sit quickly century risk many. Need according several interview south she let yeah. One point hold after fight war. Situation maybe behavior tell author should. Market become east memory area marriage.'),
  (2, 'Best reason price Mr Congress up.', 'My account show citizen just. Matter learn partner impact so address. Morning a like. Various kitchen new another. Cause know instead. Man effort three risk decide difficult while.'),
  (12, 'Hundred dog available evening only choice on.', 'Strong mission since less great little grow. Whom relate wish. Stop wear pull.'),
  (17, 'Hard fear poor picture.', 'Nation entire customer. Quality that give industry phone main first. Could per often baby very today surface.'),
  (13, 'Increase discover give indicate.', 'Yes or film outside impact resource section process. Mouth anyone early model save year. Seven program painting note imagine. Human idea company century if. And force term least turn behavior protect.'),
  (6, 'Study hotel across information second far.', 'Task teacher hard current official. The court anyone book. Mean against market deep. Everything he nothing its stock.'),
  (6, 'Future audience general do to away.', 'Attorney soldier even late. Just speech while design century. Along son red throw her major house. Board or region scene everybody. Specific receive compare million move. All brother like stand rise.'),
  (18, 'Up per manage.', 'Employee popular commercial. Summer teacher plant day matter believe. Government hard consider hot medical too local. Remain anything for her part.'),
  (11, 'Organization cover last again two example.', 'Always it can manager. Around color note debate party two physical. Where environment TV television question soldier nothing. Range agreement which floor act very institution person. Far challenge watch service point mention. Again a billion product.'),
  (20, 'Always skill production.', 'Be note positive. Rather score in laugh wide. Education analysis would situation question any everyone.'),
  (20, 'All impact end three issue way.', 'Bed church almost which. Simple tough tell cost. Successful security even almost cut learn. Friend each success last now whole save. School floor save science despite situation.'),
  (7, 'Summer recently give assume.', 'Show him measure statement could number. World get everything happen. Agent close official mouth. Allow speak man only million direction unit.'),
  (11, 'Allow leave difficult probably nor.', 'Herself item site turn million everything. Me rock everybody discover which few. Oil house soldier most attack onto tax same. Imagine score pick my language evening. Place who morning question order. True show down along economic tax them.'),
  (3, 'Floor activity gas our task.', 'Every often another discuss professional stuff house. Production course truth kitchen policy. Up right often last recent. Among partner agreement admit learn safe.'),
  (3, 'All hold focus tell have play hot.', 'Herself either western people law. Each think player yard hour forget. Mother least also reach long.'),
  (16, 'Stay suffer middle standard station.', 'Part different dream them system camera through husband. Wife during maybe sense southern free. Total born claim.'),
  (7, 'Lot wife president today become.', 'Business ever watch foreign actually. Fly collection race first catch compare example outside. Door simply business cause two.'),
  (20, 'Front nice rest city go budget free.', 'State save development I. Western ever medical PM relationship. Rather respond modern picture risk military difference.'),
  (19, 'Cut which to describe break present security.', 'Sit yes religious or bad. Floor better card direction degree. Call find boy animal well.'),
  (18, 'Mission attention those ok focus something.', 'Rule tonight every have item. Mrs major test lawyer action. Word develop rise blue play official perform example. Guess majority national performance.'),
  (18, 'Set body event pressure grow skin.', 'Spring represent professional recent financial fight purpose. Especially list situation budget act name wrong us. Main real kid amount. Opportunity need up bit bad over. Central assume daughter learn report third.'),
  (8, 'Case institution base.', 'Account summer reflect enjoy create serve with. Feeling small state. Religious can open good future member. Agree agreement medical fall. But choose machine performance force who kitchen matter.'),
  (20, 'Especially hundred apply happy executive music three.', 'Miss specific interesting summer training capital. Quite class wife newspaper. Best Republican century if notice return. Station Congress rule care example choose.'),
  (14, 'Baby door reason six hear entire well focus.', 'General production professor seven. Us indeed ago fund fight the live. Play college head official view. Including number evidence realize entire beat school.');

-- Insert comments
INSERT INTO public.comments (post_id, user_id, comment_content) VALUES
  (9, 1, 'Enjoy wide talk situation machine wife situation practice.'),
  (42, 4, 'Some media financial once more over walk themselves course camera go matter order always newspaper society.'),
  (32, 12, 'Word life thing night help nice him election share rate decade address.'),
  (5, 15, 'Body economic dream across although magazine debate can recently positive leg.'),
  (2, 19, 'Home go key check young guy common place.'),
  (15, 1, 'Thousand avoid car enter eye power few foot.'),
  (16, 13, 'Commercial thank half type speak writer quite.'),
  (14, 17, 'Hold civil much or strategy pretty nice meet admit meeting major just east.'),
  (30, 12, 'Early food reality few government move establish allow score information environment best.'),
  (27, 7, 'Door anyone pressure together finish effort whether trial phone stock investment morning big note anyone of.'),
  (29, 16, 'Need good admit interest artist research least but deep exist hit however such strong discover entire.'),
  (31, 7, 'Its a skill purpose pretty affect clear great size.'),
  (13, 8, 'Step lead floor head education have around.'),
  (11, 13, 'Purpose hard particularly take morning why while these arm voice story.'),
  (47, 18, 'Nature food begin between less institution couple figure fill.'),
  (32, 15, 'Tree today fire house wide stuff present recently age.'),
  (12, 11, 'Will son start together science central worker because sort resource.'),
  (38, 19, 'Floor senior color walk season agree strategy region treat.'),
  (5, 1, 'Thus develop high choose sort despite team hair visit anything gas where character.'),
  (47, 15, 'Popular citizen step out peace account mind street close own much citizen environmental thought language.'),
  (33, 14, 'Least group effort agreement as person family night staff.'),
  (2, 6, 'Leg wear organization before least certain author.'),
  (10, 2, 'Soldier truth Republican from from catch use human she last.'),
  (4, 20, 'Only like green kitchen movie prepare style challenge sure.'),
  (37, 3, 'Suffer never population program personal allow film health audience by watch candidate child test final travel.'),
  (35, 4, 'State television which lawyer foot prepare cultural development such air onto husband scientist teach.'),
  (14, 2, 'Suddenly fast big deal learn hundred mission system go recognize analysis draw church up behavior boy.'),
  (34, 4, 'Bed very offer stock practice game police no member full trip strategy.'),
  (26, 2, 'Require want will bring miss study specific southern lot time decision suggest.'),
  (40, 15, 'Member participant line particular window might study behind oil.'),
  (49, 14, 'Very represent bar senior list show expert beat.'),
  (27, 7, 'Air knowledge no whatever listen rather reach focus final.'),
  (16, 15, 'Animal possible surface visit five around fire store indeed analysis student simple quickly.'),
  (10, 12, 'Energy clear require see garden good there serve own memory drug skill.'),
  (36, 6, 'Interesting toward contain reduce down them year keep lot.'),
  (48, 8, 'High leg similar right base idea cover mother interview them.'),
  (25, 4, 'Ground player big about degree foot person foot alone from even finish development.'),
  (44, 15, 'Once group less record its particular budget soon.'),
  (42, 4, 'East whose factor wide including financial both compare operation at should.'),
  (40, 4, 'Sing then see population executive ability start child public certain process there.'),
  (16, 12, 'Coach mouth fear every family community between energy tend down question certainly decade during.'),
  (30, 13, 'Finally somebody manage accept Democrat woman affect thus service sing tell none during walk front green.'),
  (15, 4, 'Consider local everything while eye note apply security catch write analysis base world.'),
  (46, 12, 'Stop happy set policy paper like ground drive because worker five develop thing loss each.'),
  (28, 2, 'Out place pretty name reduce blue ten between fill thus.'),
  (19, 8, 'Offer seat wait everybody back central free reduce evidence live stand easy.'),
  (25, 16, 'Could only tonight consumer very receive somebody will effort to into.'),
  (35, 16, 'Development benefit occur marriage western despite personal financial impact of treatment while I any.'),
  (2, 5, 'Officer whether whose chance ball participant meeting feel produce many expert next between hold.'),
  (15, 18, 'Rich health source film kid minute contain of minute.'),
  (14, 7, 'Article scientist rock late mean five vote rule cultural.'),
  (23, 8, 'Down style defense investment turn reveal course write worry budget wall first change.'),
  (49, 1, 'Country including cold order dinner example own get official somebody course.'),
  (47, 17, 'Your wife house indeed food second recent throughout sometimes.'),
  (19, 19, 'Be design decade market strong production political morning.'),
  (36, 5, 'Institution film large such stay none instead generation age sense owner fight statement return modern charge.'),
  (40, 8, 'Local election before several lawyer young understand begin.'),
  (11, 5, 'Help effect cup write wall sit move light everything since cultural every possible.'),
  (29, 20, 'Reason throw task teach without wide character detail soldier central serve occur power office.'),
  (40, 4, 'Central method clear candidate production example education tell five drug smile resource choose finish.'),
  (31, 14, 'Be special throw magazine camera capital degree can imagine tend happen.'),
  (22, 7, 'Whom beat about bag child Congress member all system arrive major.'),
  (44, 8, 'Receive television remember possible mouth deal seem answer win coach film.'),
  (13, 19, 'Painting during station degree guy tough tonight authority under head strong miss traditional stay.'),
  (39, 6, 'Glass environmental act for different example director pay community.'),
  (4, 10, 'Whom usually particular customer wear affect drive science with indicate main lay image nice.'),
  (45, 8, 'Office build own never agree radio wonder society far conference pass culture use major.'),
  (43, 6, 'Cup into talk serious event and recognize decide.'),
  (20, 18, 'Machine turn notice nothing art start write.'),
  (2, 1, 'Suggest ok evidence player team because she really medical.'),
  (46, 9, 'That reduce early guy professor might foreign remember.'),
  (21, 18, 'Specific drop hope move network apply best south fly.'),
  (6, 17, 'Story base court defense too dog deal rock list century heart among defense.'),
  (50, 14, 'Success almost deal seven evening large model realize.'),
  (16, 6, 'Back film teacher former majority both dream scene third structure cost talk.'),
  (30, 9, 'If safe development nearly exist rate image.'),
  (9, 13, 'State mean political attention sister drug appear else eye go short.'),
  (11, 7, 'Article glass call go choose entire hard take young author fast.'),
  (36, 15, 'Whatever true half five mission particular guess attention ask weight next.'),
  (11, 12, 'Today like become same everyone friend window.'),
  (40, 14, 'Everything value need possible wind government write worker fire.'),
  (16, 18, 'Mean magazine morning door box good oil both fly east.'),
  (1, 15, 'Student people final other pay agent difference lawyer number.'),
  (47, 5, 'Food just thank catch sit as then weight play decision evening.'),
  (2, 11, 'Visit teach still meet region threat hospital meet close word though real.'),
  (37, 19, 'Hospital by bit scientist everything heart top miss treat food.'),
  (4, 7, 'Term stand past remember hit rather develop close turn us ability left.'),
  (46, 16, 'Fight even three talk morning agency our central when ability record seek view treat.'),
  (24, 17, 'Eight money imagine system generation across risk above thousand.'),
  (40, 5, 'Little final age enough camera example customer machine sea.'),
  (44, 14, 'Country discover speak end three on sort material finish make office feel team too join.'),
  (16, 13, 'Ever letter body suggest best western hope pay today explain.'),
  (5, 16, 'Near dream Congress must art those kind age believe behavior couple.'),
  (41, 1, 'Position power back bag two several so allow future production resource necessary close.'),
  (25, 16, 'Rest pick unit majority ready value build body air.'),
  (15, 20, 'Move statement design be in more forward well will successful she score defense.'),
  (7, 7, 'Carry real agreement think region plant raise buy live.'),
  (23, 5, 'Commercial deep thank scientist evening six policy prevent every answer item anything base to student.'),
  (37, 2, 'Record similar choice suddenly senior language summer director community rest well within quickly world.'),
  (41, 14, 'Treat door stay challenge ten huge section short well management capital civil summer fear.');